# Generated by Django 3.2 on 2021-04-20 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='halls',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
