# Generated by Django 3.2 on 2021-04-20 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_halls_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hallbookings',
            name='status',
        ),
    ]
